### ISSUE TITLE
Fault-tolerance?

### ISSUE THREAD

**Issue by eddelbuettel** [gaborcsardi/whoami#2]
So I added `whoami` to `pkgKitten` to populate `DESCRIPTION` in a better way.

Turns out that is not such a good idea Travis for two reason.  First, it adds a huge tail of `Depends:` :-/ which I can probably avoid the `r-cran-*` route.  But second, it finds nothing on empty systems:

```.R
* checking tests ...
  Running ‘simpleTest.R’
 ERROR
Running the tests in ‘tests/simpleTest.R’ failed.
Last 13 lines of output:
  
  
  	demo(simpleDemo)
  	---- ~~~~~~~~~~
  
  > library(pkgKitten)
  
  > setwd(tempdir())                        # which gets deleted anyway
  
  > kitten("simpleTest")                    # unfortunately testing fails :-/
  Error in whoami::fullname() : Cannot determine full name
  Calls: demo ... withVisible -> eval -> eval -> kitten -> ifelse -> <Anonymous>
  Execution halted
* DONE
Status: 1 ERROR
See
  ‘/home/travis/build/eddelbuettel/pkgkitten/pkgKitten.Rcheck/00check.log’
for details.
The command "./travis-tool.sh run_tests" exited with 1.
Done. Your build exited with 1.
```

Can we do better, or do you suggest I wrap this in `tryCatch()` at my end?

**Comment by gaborcsardi** [comment]
Yeah, I know, on Travis the `travis` user has no full name set. There is no way to do better, it is just not set. 

I was thinking about returning `NA`, and I am not sure which one is better. In the end, you'll need to handle the "error", and then why not make it an error?

**Comment by eddelbuettel** [comment]
Couple of options:
- document it as you appear to be aware of the issue
- offer a fallback: if **really** like the `getOption("somekey", default="fallback")` scheme
- try to catch common use cases: surely I won't be the only one trying Travis so maybe returning 'Travis User' here is ok?
- do nothing and blame users

**Comment by gaborcsardi** [comment]
Good ideas. I like the fallback, I'll do that, and also document it. Not sure about the 'Travis user', I don't like special cases too much.

**Comment by eddelbuettel** [comment]
Agreed, and with something like `fullname(fallback="Whater Bro")` it is up to me to instrument it on my side by supplying you with the fallback value I;d prefer to get back if you fail.  

Ditto for `email()`, pretty-please.

**Comment by gaborcsardi** [comment]
Actually,

**Comment by gaborcsardi** [comment]
But having many kinds of returns just complicates things, so I'll go with the original plan, and use the fallback if an empty string is returned.

**Comment by eddelbuettel** [comment]
:+1:

**Comment by eddelbuettel** [comment]
Works like a charm.  Thanks again for the quick fix.
